import { ClerkProvider, SignInButton, SignUpButton, Show, UserButton } from "@clerk/nextjs";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Source+Serif+4:wght@400;500;600;700&display=swap" rel="stylesheet" />
      </head>
      <body className="min-h-full flex flex-col">
        <ClerkProvider>
          <header className="flex justify-between items-center px-6 py-4 border-b">
            <span className="font-semibold">rlp-companion</span>
            <div className="flex gap-3 items-center">
              <Show when="signed-out">
                <SignInButton />
                <SignUpButton />
              </Show>
              <Show when="signed-in">
                <UserButton />
              </Show>
            </div>
          </header>
          {children}
          <a
            href="https://tally.so"
            target="_blank"
            rel="noopener noreferrer"
            className="fixed bottom-4 right-4 bg-black text-white text-sm px-4 py-2 rounded-full shadow-lg hover:bg-gray-800 transition-colors"
          >
            Share feedback
          </a>
        </ClerkProvider>
      </body>
    </html>
  );
}