import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Source+Serif+4:wght@400;500;600;700&display=swap" rel="stylesheet" />
      </head>
      <body className="min-h-full flex flex-col">
        <ClerkProvider>
          {children}
          {/* Global feedback button — fixed bottom-right on every screen. */}
          <a
            href="https://tally.so"
            target="_blank"
            rel="noopener noreferrer"
            style={{
              position: "fixed",
              right: "22px",
              bottom: "22px",
              background: "var(--ink)",
              color: "#fff",
              border: "none",
              borderRadius: "var(--r-pill)",
              padding: "11px 18px",
              fontSize: "13px",
              fontWeight: 600,
              boxShadow: "var(--shadow-md)",
              display: "flex",
              alignItems: "center",
              gap: "7px",
              zIndex: 20,
            }}
          >
            💬 Feedback
          </a>
        </ClerkProvider>
      </body>
    </html>
  );
}