// Selection logic for the on-load takeaway self-heal, kept here (pure, no React
// or Clerk) so it's unit-testable independently of the data layer that runs it.
//
// A session's takeaway is generated by a fire-and-forget background call when the
// person wraps up (SessionContainer.generateAndStoreTakeaway) — no retry, no
// persistence guarantee — so a reload or an immediate jump to the next session
// can drop it, leaving a completed session with no takeaway. The data layer heals
// that on load by regenerating from the stored transcript; this decides which
// sessions qualify.

import { allModulesInOrder } from "@/lib/modules";
import type { ConversationMessage } from "@/lib/userData";

export type HealTarget = {
  id: string;
  moduleTitle: string;
  messages: ConversationMessage[];
};

// The completed sessions that have a real conversation but no saved takeaway. A
// session qualifies only when it is a real module (so we have a title to store),
// has no takeaway yet, and its conversation contains at least one thing the
// person actually said — there is nothing to summarise otherwise, and we must
// never invent content. The data layer passes the lookups so this stays pure.
export function sessionsNeedingTakeaway(params: {
  completed: unknown;
  hasTakeaway: (id: string) => boolean;
  getConversation: (id: string) => ConversationMessage[] | null;
}): HealTarget[] {
  const { completed, hasTakeaway, getConversation } = params;
  if (!Array.isArray(completed)) return [];

  const titleById = new Map(allModulesInOrder().map((m) => [m.id, m.title]));
  const targets: HealTarget[] = [];

  for (const id of completed) {
    if (typeof id !== "string") continue;
    if (hasTakeaway(id)) continue;
    const moduleTitle = titleById.get(id);
    if (!moduleTitle) continue; // not a real module (e.g. the stage1-start id)
    const messages = getConversation(id) ?? [];
    if (!messages.some((m) => m?.role === "user" && m.text?.trim())) continue;
    targets.push({ id, moduleTitle, messages });
  }

  return targets;
}
